[package]
name = "neatcoin"
version = "0.1.0"
authors = ["Wei Tang <wei@that.world>"]
edition = "2018"
license = "GPL-3.0-or-later"
build = "build.rs"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", features = ["wasmtime"] }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", features = ["wasmtime"] }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", features = ["wasmtime"] }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sp-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sc-finality-grandpa = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate" }
substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }
frame-benchmarking-cli = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }

neatcoin-runtime = { version = "0.1.0", path = "runtime" }

funty = "=1.1.0"

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate" }

[features]
default = []
runtime-benchmarks = [
	"neatcoin-runtime/runtime-benchmarks",
]

[workspace]
members = [
	"runtime",
	"frame/outmove",
]